version: "3.8"

services:  
  mysql-db:
    image: mysql:latest
    container_name: mysql_docker
    restart: always
    ports:
      - 13306:3306
    volumes:
      - my-data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eldorado-mecanica
    networks:
      - mysql-compose-network

  data-db:
    container_name: mysql_data
    image: mysql:latest
    volumes:
      - ./backend/data:/var/lib/mysql:rw
    command: "true"

  adminer:
    image: adminer
    container_name: adminer_docker
    ports:
      - 18080:8080
    depends_on:
      - mysql-db
    networks:
      - mysql-compose-network
volumes:
  my-data-volume:
networks:
  mysql-compose-network:
    driver: bridge
