"""empty message

Revision ID: 8a0835a5aae4
Revises: 
Create Date: 2022-03-20 19:18:40.299918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a0835a5aae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_car')
    op.drop_table('users')
    op.drop_table('cars_model')
    op.drop_table('services')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars_model',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('model', mysql.VARCHAR(
                        length=250), nullable=True),
                    sa.Column('manufacturer', mysql.VARCHAR(
                        length=250), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(
                        length=250), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_car',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('characteristics', mysql.VARCHAR(
                        length=250), nullable=True),
                    sa.Column('license_plate', mysql.VARCHAR(
                        length=100), nullable=True),
                    sa.Column('client_id', mysql.INTEGER, nullable=True),
                    sa.Column('car_model_id', mysql.INTEGER, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['car_model_id'], ['cars_model.id'], ),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )

    op.create_table('services',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(
                        length=250), nullable=True),
                    sa.Column('description', mysql.VARCHAR(
                        length=250), nullable=True),
                    sa.Column('time_service', mysql.VARCHAR(
                        length=100), nullable=True),
                    sa.Column('price', mysql.DECIMAL(10, 2), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )

    op.create_table('order',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('order_number', mysql.INTEGER, nullable=True),
                    sa.Column('service_id', mysql.INTEGER, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
